### ISSUE TITLE
Do you still have the CSV files and the SIPP command line?

### ISSUE THREAD

**Issue by gtjoseph** [flaviogoncalves/astricon2017#1]
Hi Flavio,

I just watched the YouTube video of your AstriCon 2017 presentation and the results of the registration test are pretty strange.  Do you still have the csv file you used to drive the sipp tests and the command line you used?  I'd like to try and recreate the results and see what's going on.

Thanks!  It was a good presentation!

George Joseph
Asterisk Developer

**Comment by flaviogoncalves** [comment]
Hi George,

I can check, but it was a long time ago. What I have is on the github.  The
computer I used to make the tests was formatted.

https://github.com/flaviogoncalves/astricon2017

The command line is on the presentation attached below.

client2.csv is a simple file for authentication, similar to below. I've
used an utility to generate 2 or 3 thousand users, I don't remember
exactly.

Example:

SEQUENTIAL
600000;demo.sippulse.com;[authentication username=600000 password=600000];

I hope it helps,


Flavio E. Goncalves
V.Office Redes e Telecomunicações Ltda.
Fone 48 33328590
Skype:flaviogoncalves1
Linkedin: www.linkedin.com/in/flavioegoncalves


2018-03-20 14:08 GMT-03:00 George Joseph <notifications@github.com>:

**Comment by gtjoseph** [comment]
Thanks Flavio!  Sounds like nothing special in the sipp scenarios so I should be able to reproduce.
